Require Node.js 10
sindresorhus/gzip-size pull request #20
Opened 2020-11-04 21:54 UTC by realityking

This nicely gets rid of the dependency of `pify`.

2020-11-13 14:18 UTC, realityking commented
@sindresorhus Could you take a look at this one? 🙏

2020-11-14 23:48 UTC, sindresorhus requested changes

2020-11-14 23:48 UTC, sindresorhus commented on index.js
> +	const data = await promisify(zlib.gzip)(input, getOptions(options));
It's generally better to do the promisification at the top-level if it doesn't require any local state, so it doesn't have to be done for each function invocation.

2020-11-14 23:48 UTC, sindresorhus commented on index.js
The `Promise.resolve` is moot now.

2020-11-14 23:48 UTC, sindresorhus commented on package.json
> +		"typescript": "^4.0.5",
This is not needed.

2020-11-16 11:01 UTC, merged